inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

# rubocop fix lifted from CirrusSearch/.rubocop.yml
Style/LeadingCommentSpace:
  Exclude:
    - Gemfile  # RVM doesn't recognise spaces after the #s

Style/SignalException:
  Enabled: false
