function ($cx, $in, $sp) {return ''.$sp.'<div class="flow-board">
'.$sp.''.LR::p($cx, 'flow_errors', array(array($in),array()),0, '	').'
'.$sp.''.((LR::ifvar($cx, ((is_array($in) && isset($in['revision'])) ? $in['revision'] : null), false)) ? '		<div class="flow-revision-permalink-warning plainlinks">
'.$sp.''.((LR::ifvar($cx, ((isset($in['revision']) && is_array($in['revision']) && isset($in['revision']['previousRevisionId'])) ? $in['revision']['previousRevisionId'] : null), false)) ? '				'.LR::encq($cx, LR::hbch($cx, 'l10nParse', array(array('flow-revision-permalink-warning-header',((isset($in['revision']) && is_array($in['revision']) && isset($in['revision']['human_timestamp'])) ? $in['revision']['human_timestamp'] : null),((isset($in['revision']['rev_view_links']['hist']) && is_array($in['revision']['rev_view_links']['hist']) && isset($in['revision']['rev_view_links']['hist']['url'])) ? $in['revision']['rev_view_links']['hist']['url'] : null),((isset($in['revision']['rev_view_links']['diff']) && is_array($in['revision']['rev_view_links']['diff']) && isset($in['revision']['rev_view_links']['diff']['url'])) ? $in['revision']['rev_view_links']['diff']['url'] : null)),array()), 'encq', $in)).'
'.$sp.'' : '				'.LR::encq($cx, LR::hbch($cx, 'l10nParse', array(array('flow-revision-permalink-warning-header-first',((isset($in['revision']) && is_array($in['revision']) && isset($in['revision']['human_timestamp'])) ? $in['revision']['human_timestamp'] : null),((isset($in['revision']['rev_view_links']['hist']) && is_array($in['revision']['rev_view_links']['hist']) && isset($in['revision']['rev_view_links']['hist']['url'])) ? $in['revision']['rev_view_links']['hist']['url'] : null),((isset($in['revision']['rev_view_links']['diff']) && is_array($in['revision']['rev_view_links']['diff']) && isset($in['revision']['rev_view_links']['diff']['url'])) ? $in['revision']['rev_view_links']['diff']['url'] : null)),array()), 'encq', $in)).'
'.$sp.'').'		</div>
'.$sp.'
'.$sp.'		<div class="flow-revision-content">
'.$sp.'			'.LR::encq($cx, LR::hbch($cx, 'escapeContent', array(array(((isset($in['revision']['content']) && is_array($in['revision']['content']) && isset($in['revision']['content']['format'])) ? $in['revision']['content']['format'] : null),((isset($in['revision']['content']) && is_array($in['revision']['content']) && isset($in['revision']['content']['content'])) ? $in['revision']['content']['content'] : null)),array()), 'encq', $in)).'
'.$sp.'		</div>
'.$sp.'
'.$sp.''.LR::p($cx, 'flow_patrol_action', array(array($in),array()),0, '		').'' : '').'</div>
';}