#!/bin/sh

# TODO: share is_vagrant and make functions between scripts
is_vagrant() {
        DEST='.'
        while [ "$(realpath $DEST)" != "/" ]; do
                if [ -f $DEST/Vagrantfile ]; then
                        return 0;
                fi
                DEST="$DEST/.."
        done
        return 1
}

make() {
        if is_vagrant; then
                vagrant ssh -- cd /vagrant/mediawiki/extensions/Flow '&&' make $* || exit 1
        else
                /usr/bin/env make $* || exit 1
        fi
}

# only checks top commit for changes

if git diff-tree --no-commit-id --name-only -r HEAD | grep -P '\.php$'; then
	# bit of a hack ... other things run inside vagrant but phpstorm is probably
	# installed external to vagrant
	/usr/bin/env make analyze-phpstorm
fi

if git diff-tree --no-commit-id --name-only -r HEAD | grep -P '\.i18n\.php$'; then
	COMMANDS="check-i18n $COMMANDS"
fi

if [ "$COMMANDS" != "" ]; then
	make $COMMANDS || exit 1
fi

